      SUBROUTINE MAXMIN (F, FMASK, IX, JY, FMAX , FMIN)
C     VERSION(03/02/90)
      DIMENSION F(IX,JY),FMASK(IX,JY)
C
      DATA BIG/1.E20/
C
      FMAX=-BIG
      FMIN=BIG
      DO 220 J=1, JY
      DO 220 I=1, IX
      IF(FMASK(I,J).EQ.0.) GO TO 220
      FMAX=AMAX1(FMAX,F(I,J))
      FMIN=AMIN1(FMIN,F(I,J))
  220 CONTINUE
C
      RETURN
      END
