      SUBROUTINE SLICEYZ(FD,AMASK,IM,JM,KB,IROW,ARRAY,SCALE,IUNIT)
C     VERSION(03/02/90)
C
      DIMENSION FD(IM,JM,KB),ARRAY(JM,1)
      DIMENSION AMASK(JM,1)
C
      WRITE(IUNIT,5) IROW
 5    FORMAT(///' VERTICAL SECTION AT COLUMN = ',I3///)
C
      DO 10 K=1,KB
      DO 10 J=1,JM
 10   ARRAY(J,K)=FD(IROW,J,K)
C
      CALL DISPLY(ARRAY,AMASK,JM,0,KB,SCALE,IUNIT)
C
      RETURN
      END
