      SUBROUTINE SLICEXZ(FD,AMASK,IM,JM,KB,JROW,ARRAY,SCALE,IUNIT)
C     VERSION(03/02/90)
C
      DIMENSION FD(IM,JM,KB),ARRAY(IM,1)
      DIMENSION AMASK(IM,1)
C
      WRITE(IUNIT,5) JROW
 5    FORMAT(///27H VERTICAL SECTION AT ROW = ,I3///)
C
      DO 10 K=1,KB
      DO 10 I=1,IM
 10   ARRAY(I,K)=FD(I,JROW,K)
C
      CALL DISPLY(ARRAY,AMASK,IM,0,KB,SCALE,IUNIT)
C
      RETURN
      END
      
